---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: ${NAMESPACE}
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  url: ${GITHUB_URL}
  username: bm90LXVzZWQ=
  password: ${GITHUB_TOKEN}
type: Opaque

